import { useMount } from 'react-use'

import { useScene } from '~/stores/Scene.store'

import { GameLayout } from '../components/GameLayout'

function Header() {
  return (
    <span>
      <span>Is this image generated by </span>
      <span className="bg-[linear-gradient(180deg,#E3FFB5_0%,#9E95FF_60.09%,#0E7FA3_100%,#712E91_100%,#D57DFF_100%)] bg-clip-text text-transparent">
        AI
      </span>
      <span> ?</span>
    </span>
  )
}

export function WarmUp() {
  const { switchScene } = useScene()

  useMount(() => {
    setTimeout(() => {
      localStorage.setItem('hasWarmedUp', 'true')
      switchScene('READY')
    }, 3000)
  })

  return <GameLayout header={<Header />}>WarmUp...</GameLayout>
}
