import { useMount } from 'react-use'

import { useScene } from '~/stores/Scene.store'

import { BorderWithoutCorner } from '../components/BorderWithoutCorner'
import { GameLayout } from '../components/GameLayout'

function Header() {
  return (
    <span>
      <span>Is this image generated by </span>
      <span className="bg-[linear-gradient(180deg,#E3FFB5_0%,#9E95FF_60.09%,#0E7FA3_100%,#712E91_100%,#D57DFF_100%)] bg-clip-text text-transparent">
        AI
      </span>
      <span> ?</span>
    </span>
  )
}

export function WarmUp() {
  const { switchScene } = useScene()

  const skipWarmUp = () => {
    localStorage.setItem('hasWarmedUp', 'true')
    switchScene('READY')
  }

  useMount(() => {
    setTimeout(() => {
      skipWarmUp()
    }, 3000)
  })

  return (
    <GameLayout header={<Header />} className="relative h-full w-full">
      <h1>Warm up...</h1>
      <button
        className="absolute right-[20px] top-[20px] block h-fit w-fit p-[6px] text-[14px] sm:bottom-[77px] sm:right-[40px] sm:top-auto"
        onClick={skipWarmUp}
      >
        <BorderWithoutCorner width={4} />
        Skip&gt;&gt;
      </button>
    </GameLayout>
  )
}
