import Image from 'next/image'

interface GameLayoutProps {
  children: React.ReactNode
  header?: React.ReactNode
  className?: string
}

function DefaultHeader() {
  return (
    <span>
      <span>Is this image generated by </span>
      <span className="bg-[linear-gradient(180deg,#E3FFB5_0%,#9E95FF_60.09%,#0E7FA3_100%,#712E91_100%,#D57DFF_100%)] bg-clip-text text-transparent">
        AI
      </span>
      <span> ?</span>
    </span>
  )
}

export function GameLayout({ children, header, className }: GameLayoutProps) {
  return (
    <div className="relative h-[100dvh] border-[12px] border-[#717171] p-[12px] sm:border-[24px] sm:bg-[#2D2D2D] sm:p-[34px]">
      <div className="absolute left-[-12px] top-[-12px] h-[12px] w-[12px] bg-black sm:left-[-24px] sm:top-[-24px] sm:h-[24px] sm:w-[24px] sm:bg-[#2D2D2D]" />
      <div className="absolute right-[-12px] top-[-12px] h-[12px] w-[12px] bg-black sm:right-[-24px] sm:top-[-24px] sm:h-[24px] sm:w-[24px] sm:bg-[#2D2D2D]" />
      <div className="absolute bottom-[-12px] left-[-12px] h-[12px] w-[12px] bg-black sm:bottom-[-24px] sm:left-[-24px] sm:h-[24px] sm:w-[24px] sm:bg-[#2D2D2D]" />
      <div className="absolute bottom-[-12px] right-[-12px] h-[12px] w-[12px] bg-black sm:bottom-[-24px] sm:right-[-24px] sm:h-[24px] sm:w-[24px] sm:bg-[#2D2D2D]" />
      <div className="relative h-full border-[10px] border-white bg-[#505050] px-[12px] sm:px-[32px]">
        <div className="absolute left-[-10px] top-[-10px] hidden h-[27px] w-[27px] bg-white sm:block" />
        <div className="absolute right-[-10px] top-[-10px] hidden h-[27px] w-[27px] bg-white sm:block" />
        <div className="absolute bottom-[-10px] left-[-10px] hidden h-[27px] w-[27px] bg-white sm:block" />
        <div className="absolute bottom-[-10px] right-[-10px] hidden h-[27px] w-[27px] bg-white sm:block" />
        <div className="absolute left-[-12px] top-[-12px] h-[12px] w-[12px] bg-black sm:left-[-10px] sm:top-[-10px] sm:h-[17px] sm:w-[17px] sm:bg-[#2D2D2D]" />
        <div className="absolute right-[-12px] top-[-12px] h-[12px] w-[12px] bg-black sm:right-[-10px] sm:top-[-10px] sm:h-[17px] sm:w-[17px] sm:bg-[#2D2D2D]" />
        <div className="absolute bottom-[-12px] left-[-12px] h-[12px] w-[12px] bg-black sm:bottom-[-10px] sm:left-[-10px] sm:h-[17px] sm:w-[17px] sm:bg-[#2D2D2D]" />
        <div className="absolute bottom-[-12px] right-[-12px] h-[12px] w-[12px] bg-black sm:bottom-[-10px] sm:right-[-10px] sm:h-[17px] sm:w-[17px] sm:bg-[#2D2D2D]" />
        <div className="flex h-[60px] items-center justify-between sm:h-[52px]">
          <div className="w-[24px] items-center text-[12px] sm:flex sm:w-[136px] sm:gap-[4px]">
            <Image
              src="/images/logo.svg"
              alt="logo"
              className="h-[24px] w-[24px]"
              width={24}
              height={24}
            />
            <span className="hidden sm:block">Isthat.ai</span>
          </div>
          <div className="text-center text-[12px] sm:text-[16px]">
            {header || <DefaultHeader />}
          </div>
          <div className="w-[24px] sm:w-[136px]"></div>
        </div>
        <div className="h-[calc(100%-72px)] bg-black sm:h-[calc(100%-84px)]">
          <div className="flex h-full items-center justify-center bg-[linear-gradient(#2d2d2d_1px,transparent_1px)] bg-[length:100%_16px] sm:bg-[length:100%_24px]">
            <div className={className}>{children}</div>
          </div>
        </div>
      </div>
    </div>
  )
}
